<def f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/Debugger.h' l='232' type='void JSC::Debugger::reportException(JSC::JSGlobalObject * , JSC::Exception * ) const'/>
<doc f='webkit/WebKitBuild/Debug/JavaScriptCore.framework/Versions/A/PrivateHeaders/Debugger.h' l='229'>// NOTE: Currently all exceptions are reported at the API boundary through reportAPIException.
    // Until a time comes where an exception can be caused outside of the API (e.g. setTimeout
    // or some other async operation in a pure JSContext) we can ignore exceptions reported here.</doc>
<ovr f='webkit/Source/WebCore/inspector/PageDebugger.cpp' l='141' c='_ZNK7WebCore12PageDebugger15reportExceptionEPN3JSC14JSGlobalObjectEPNS1_9ExceptionE'/>
<use f='webkit/Source/WebCore/inspector/PageDebugger.cpp' l='143' u='c' c='_ZNK7WebCore12PageDebugger15reportExceptionEPN3JSC14JSGlobalObjectEPNS1_9ExceptionE'/>
<ovr f='webkit/Source/WebCore/inspector/WorkerDebugger.cpp' l='88' c='_ZNK7WebCore14WorkerDebugger15reportExceptionEPN3JSC14JSGlobalObjectEPNS1_9ExceptionE'/>
<use f='webkit/Source/WebCore/inspector/WorkerDebugger.cpp' l='90' u='c' c='_ZNK7WebCore14WorkerDebugger15reportExceptionEPN3JSC14JSGlobalObjectEPNS1_9ExceptionE'/>
